### ISSUE TITLE
libcsound64.so not found

### ISSUE THREAD

**Issue by uummoo** [fggp/ctcsound#6]
Hello everybody,

when I try to import the ctcsound module in a python3 interpreter, I got the following error message:

```python
import ctcsound
```
> OSError: libcsound64.so: cannot open shared object file: No such file or directory

I use Ubuntu 17.10 64 bit Version and I have a installed Csound version 6.09.1 (double samples) (installed via apt-get) on my computer.

I tried to import the ctcsound module, which I cloned from this Github repository. The shell doesn't find the libcsound64.so - file neither:

```
find / libcsound64.so
```

> find: ‘libcsound64.so’: No such file or directory

Do I have to install Csound differently?

**Comment by uummoo** [comment]
I found libcsound64.so.6.0 in usr/lib. I changed the ctcsound.py - file to:
```python
if sys.platform.startswith('linux'):
    libcsound = CDLL("libcsound64.so.6.0")
```


Unfortunately I get an error:
```python
import ctcsound
```
> AttributeError: /usr/lib/libcsound64.so.6.0: undefined symbol: csoundCompileTreeAsync

**Comment by fggp** [comment]
You should  create a symlink to libcsound64.so.6.0 in usr/lib:
cd /usr/lib
sudo ln -s libcsound64.so.6.0 libcsound64.so

It's a cleaner way.

Then the Attribute error is due to the fact that the csoundCompileTreeAsync method didn't exist in Csound6.09.01. You should use the ctcsound.py file shipped within the apt package instead. The ctcsound.py file in the github repo is synced with the develop branch of Csound and thus it can refer to methods that don't exist in earlier versions of Csound.
